apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: AWSMachineTemplate
metadata:
  name: cluster-control-plane
spec:
  template:
    spec:
      sshKeyName: dev
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: AWSMachineTemplate
metadata:
  name: cluster-md-0
spec:
  template:
    spec:
      sshKeyName: dev
