apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#namePrefix: dev-

commonLabels:
  variant: dev

commonAnnotations:
  note: dev cluster

resources:
  - ../../base

patchesStrategicMerge:
  - aws-cluster.yml
  - aws-machine-template.yml
  - cluster.yml
  - kubeadm-config-template.yml
  - kubeadm-control-plane.yml
  - machine-deployment.yml