apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: clusters
  namespace: argocd
  labels:
    group: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/cohencil/k8s-clusters.git
    path: clusters/envs/local-cluster
    targetRevision: master
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy: {}
